### ISSUE TITLE
truecrypt PIE

### ISSUE THREAD

**Issue by shelleyfrank** [neurodroid/cryptonite#101]
When I try to execute truecrypt in android terminal I get the following:

`error: only position independent executables (PIE) are supported.`

Could you compile a truecrypt binary with PIE support and add it here for download please?

**Comment by neurodroid** [comment]
There are a couple of PIE versions here:
https://github.com/neurodroid/cryptonite/releases
I'm not maintaining cryptonite at this time, but I'd be happy to provide support if you want to build it from source.

**Comment by shelleyfrank** [comment]
Hallo!
Thanks for your email and the link. I got a truecrypt binary working on my 
phone by extracting it from the latest cryptonite apk and combining the two 
part file. It works, although I get an error message at the front of every 
operation,

Error: Cannot convert from the charset  'encoding - 1'

It doesn't appear to affect any truecrypt operations though. I'm busy 
moving house from Delhi to London right now, including my Indian cat! When 
I'm settled in I will set up my computer and try and build it from source. 
Thanks once again for offering support to build it. That's very kind of you.

Best wishes
Michael Pienaar

**Comment by yuanh1128** [comment]
I have the same problem with my cellphone. The error message is "Error: Cannot convert from the charset  'encoding - 1' ". It seems that there is something wrong with the charset . I wonder where this message comes from, from truecrypt or the android system or the linux kernel?
