### ISSUE TITLE
Mounting fails without error message

### ISSUE THREAD

**Issue by btongminh** [neurodroid/cryptonite#104]
Mounting a volume fails without an error message. I logged the command that cryptonite uses, replayed it in an adb shell, and there it works. Output of logcat does not show anything of interest.

Any idea how to further debug this?

**Comment by neurodroid** [comment]
This has been previously reported a couple of times - please go through the list of open issues.

I'm no longer actively maintaining this app, so someone else will have to step in.

Closing this for now.
