### ISSUE TITLE
OSX fuse usage

### ISSUE THREAD

**Issue by konsumer** [neurodroid/cryptonite#106]
Hi! I'd love a copy of the folder-icon file you use for OSX fuse-mounting. Looked around at the .icns files in the Dropbox app, but wasn't sure which was the right one. Here are the ones in `/Applications/Dropbox.app/Contents/Resources`:

```
DropboxAppFolderIcon.icns
DropboxAppFolderIconYosemite.icns
DropboxFolderIcon.icns
DropboxFolderIconYosemite.icns
DropboxPublicFolderIcon.icns
DropboxPublicFolderIconYosemite.icns
DropboxReadOnlySharedFolderIcon.icns
DropboxReadOnlySharedFolderIconYosemite.icns
DropboxReadOnlyTeamFolderIcon.icns
DropboxReadOnlyTeamFolderIconYosemite.icns
DropboxTeamFolderIcon.icns
DropboxTeamFolderIconYosemite.icns
emblem-dropbox-infinite.icns
emblem-dropbox-mixedstate.icns
emblem-dropbox-selsync.icns
emblem-dropbox-syncing.icns
emblem-dropbox-unsyncable.icns
emblem-dropbox-uptodate.icns
icon.icns
```

Also, I use `brew` instead of `port` and installed it like this:

```
brew cask install osxfuse
brew install homebrew/fuse/encfs
```

I dunno if you want to add that to the README, but it works great.

**Comment by konsumer** [comment]
Also, it might be helpful to others to add a link to [encfsmp](http://encfsmp.sourceforge.net/), which is a nice frontend for Mac & Win.

**Comment by neurodroid** [comment]
See https://github.com/neurodroid/cryptonite/commit/bc029983
Regarding the documentation, please send me a pull request with your suggested changes.
Not sure you'll be able to _build_ cryptonite with homebrew tools though.

**Comment by konsumer** [comment]
Ah, I see, it's just the Dropbox logo for the drive, not a collection of folder status icons for individual files.

Will do with README PR.

As for homebrew building cryptonite, I'm not sure what you mean. It installs encfs version 1.9.0. Building should work the same, and not need anything from port, right?

**Comment by neurodroid** [comment]
@konsumer Thanks

**Comment by konsumer** [comment]
@neurodroid Thank you! Awesome and useful app.
