### ISSUE TITLE
Truecrypt - Error: Cannot convert from the charset 'encoding - 1'

### ISSUE THREAD

**Issue by konst-py** [neurodroid/cryptonite#112]
Hello,

I get an error message at the front of every operation, but unlike  shelleyfrank(issue101), it don't work on my phone.
if I list mounted volumes after mounting I can see 2 identical volumes, but in mountfolder there no files. I tried binary from latest criptonite apk (Cryptonite-BETA-0.7.17.apk) and I buid it self. Any suggestions?

**Comment by konst-py** [comment]
There second error in output at mount attempt.
Error: Failed to set up a loop device:
/sdcard/Android/data/csh.cryptonite/.truecrypt_aux_mnt2/volume

**Comment by viche12345** [comment]
Hi konst-py,

Any luck with this issue yet? I'm having the same loop device problem on Android 6.0.1

**Comment by konst-py** [comment]
No, I downloaded  loop device checker from GP. It seems that my kernel doesn't support loop devices. thats sucks :((

**Comment by viche12345** [comment]
Same with me :(

Guess it's time to try a new ROM. Thanks for replying though.
