### ISSUE TITLE
Supplementary tools (unmount, change password)

### ISSUE THREAD

**Issue by BlueMax** [neurodroid/cryptonite#84]
Hi,
can you provide the supplementary tools 'fusermount' and 'encfsctl' as well so we can gracefully unmount and change passwords of mounted folders?

**Comment by neurodroid** [comment]
encfsctl is generated during the build process, but it's too large to be packaged with the cryptonite apk - it would more than double its size.
I've never tried to build fusermount for Android. Looking at the [code](http://sourceforge.net/p/fuse/fuse/ci/master/tree/util/fusermount.c), it makes many assumptions that will only hold for desktop Linux distributions but not for Android - I doubt it would be useful or even run without major modifications.

**Comment by BlueMax** [comment]
Maybe one can copy the metafile to desktop system to change the password there (not checked yet). But more important is unmounting. The binary already supports auto-unmounting if i get that right. Can you modify it maybe somehow to support manual unmounting as well?

**Comment by neurodroid** [comment]
You should be able to use umount for unmounting.

**Comment by BlueMax** [comment]
You're right. On a second test i can unmount it without problems. Not sure why it didn't work for me previously. I didn't even get an error message. Unmounting looked properly at first but the mounted content was still there. So yes, fusermount is useless then indeed. I thought it would be mandatory for unmounting. Sorry for any inconvenience.
Can you provide the encfsctl binary externally on your homepage so we can optionally get it on demand?

**Comment by neurodroid** [comment]
> Can you provide the encfsctl binary externally on your homepage
> so we can optionally get it on demand?

https://github.com/neurodroid/cryptonite/releases/tag/v0.7.12

**Comment by BlueMax** [comment]
Thank you very much. :)
