### ISSUE TITLE
Do I need all the release files?

### ISSUE THREAD

**Issue by gerroon** [neurodroid/cryptonite#86]
Hi

I would like to give this a try and I will use the bleeding edge releases. Will I need all the files under the release page to use this? Is the apk file enough for Android? 

There is no help page for these releases so I am filing it a bug.

thanks

**Comment by neurodroid** [comment]
No you don't need all files - the apk is enough. I'd recommend to go with [v0.7.12](https://github.com/neurodroid/cryptonite/releases/tag/v0.7.12).

**Comment by gerroon** [comment]
thanks
