### ISSUE TITLE
error: only position independent executables (PIE) are supported.

### ISSUE THREAD

**Issue by dimovnike** [neurodroid/cryptonite#90]
I get this error when trying to run the binary.

root@hammerhead:/ # /data/data/csh.cryptonite/encfs
error: only position independent executables (PIE) are supported.

Nexus5, Cyanogenmod cm12, android 5.0.2
any idea?
Thanks!

**Comment by neurodroid** [comment]
Is this with the latest version (v0.7.17)? See issue #83

**Comment by dimovnike** [comment]
Ah yes, downloaded the newer binary from "Cryptonite Android package and encfs 1.7.5 PIE binaries" and now it works, thanks!
Now I have another issue - how to mount a directory from adb shell so its visible to other apps? I understand that android uses separate namespaces but how to make a mount in the "apps namespace". Basically im trying to use --reverse feature from the shell.

**Comment by dimovnike** [comment]
im closing this then, thanks again (will create another issue related to mounting).
