### ISSUE TITLE
.encfs6.xml file

### ISSUE THREAD

**Issue by Slim1991** [neurodroid/cryptonite#96]
Hi,
Can you tell me the structure of this xml file? What is underlying?
I want to understand this file.

**Comment by neurodroid** [comment]
Cryptonite is an Android wrapper around [EncFS](https://vgough.github.io/encfs/). As I know very little about the encfs configuration file format, you should direct your question to the encfs developers.

**Comment by Slim1991** [comment]
Thank you!
If you know anything, just tell me.
